import React, { useState } from 'react';
import { useValueTogether } from '../context/ValueTogetherContext';
import { PageBanner } from '../components/common/PageBanner';
import { Banknote, HeartHandshake, ReceiptText, ShieldCheck, CheckCircle2 } from 'lucide-react';
import { checkRateLimit } from '../utils/spamGuard';

export const DonationPage: React.FC = () => {
 const { settings, submitDonationInquiry } = useValueTogether(); const account=settings.bankAccounts?.[0];
 const [name,setName]=useState('');const [phone,setPhone]=useState('');const [email,setEmail]=useState('');const [amount,setAmount]=useState('');const [purpose,setPurpose]=useState('');const [receipt,setReceipt]=useState(false);const [agree,setAgree]=useState(false);const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);const [error,setError]=useState('');
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');const numeric=Number(amount.replace(/,/g,''));if(!name.trim()||!phone.trim()||!numeric||numeric<1000){setError('이름·연락처와 1,000원 이상의 후원 예정 금액을 입력해 주세요.');return;}if(!agree){setError('개인정보 수집·이용에 동의해 주세요.');return;}const limit=checkRateLimit('gachihamkke_donation_submit',3,10*60*1000);if(!limit.allowed){setError('잠시 후 다시 신청해 주세요.');return;}setBusy(true);try{await submitDonationInquiry({donorName:name.trim(),phone:phone.trim(),email:email.trim()||undefined,amount:numeric,purpose:purpose.trim()||undefined,receiptRequested:receipt,privacyAgreed:true});setDone(true);}catch{setError('후원 신청 접수에 실패했습니다. 잠시 후 다시 시도해 주세요.');}finally{setBusy(false);}};
 return <div><PageBanner eyebrow="DONATION" title="후원하기" description="가치함께의 공익적 활동을 응원하는 가장 따뜻한 방법입니다."/><div className="max-w-6xl mx-auto px-4 sm:px-6 py-10 sm:py-14 space-y-12">
  <section className="grid md:grid-cols-3 gap-4"><Info icon={HeartHandshake} title="일시·정기 후원" text="조합이 안내하는 후원계좌를 통해 후원하실 수 있습니다."/><Info icon={Banknote} title="사용처 공개" text="기부금 모금 및 활용실적은 관련 규정에 따라 공개 가능한 범위에서 안내합니다."/><Info icon={ReceiptText} title="영수증 요청" text="기부금 영수증 발급 여부와 절차는 조합의 법적 자격 및 세무 요건을 확인하여 처리합니다."/></section>
  <section className="grid lg:grid-cols-[.8fr_1.2fr] gap-8 items-start"><div className="bg-secondary-soft/60 border border-secondary-soft rounded-3xl p-6 sm:p-8"><h2 className="font-display font-black text-2xl text-ink">후원계좌</h2>{account?<div className="mt-5 space-y-2"><p className="text-sm text-ink-soft">은행</p><p className="font-bold text-ink text-lg">{account.bank}</p><p className="text-sm text-ink-soft mt-4">계좌번호</p><p className="font-bold text-ink text-lg break-all">{account.accountNumber}</p><p className="text-sm text-ink-soft mt-4">예금주</p><p className="font-bold text-ink">{account.holder}</p></div>:<p className="text-sm text-ink-soft mt-4">후원계좌는 관리자 확인 후 홈페이지에 등록됩니다.</p>}<div className="mt-7 flex gap-2 text-xs text-ink-soft"><ShieldCheck className="w-4 h-4 text-secondary-ink"/>출자금과 후원금은 별도로 관리합니다.</div></div>
  <div className="bg-paper-card border border-line rounded-3xl p-6 sm:p-8">{done?<div className="py-10 text-center"><CheckCircle2 className="w-12 h-12 text-secondary-ink mx-auto"/><h2 className="font-display font-black text-xl text-ink mt-4">후원 의향이 접수되었습니다.</h2><p className="text-sm text-ink-soft mt-2">입금 확인 및 영수증 관련 사항을 담당자가 안내드리겠습니다.</p></div>:<form onSubmit={submit} className="space-y-4"><h2 className="font-bold text-ink text-lg">후원 의향 등록</h2><div className="grid sm:grid-cols-2 gap-4"><Field label="성명 *"><input className={inputCls} value={name} onChange={e=>setName(e.target.value)} required/></Field><Field label="연락처 *"><input className={inputCls} value={phone} onChange={e=>setPhone(e.target.value)} required/></Field></div><Field label="이메일"><input type="email" className={inputCls} value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="후원 예정 금액 *"><input inputMode="numeric" className={inputCls} value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9,]/g,''))} placeholder="예: 100,000"/></Field><Field label="후원 목적"><input className={inputCls} value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="예: 지역사회 교육 지원"/></Field><label className="flex gap-2.5 text-xs text-ink-soft"><input type="checkbox" checked={receipt} onChange={e=>setReceipt(e.target.checked)} className="mt-0.5"/><span>기부금 영수증 발급 가능 여부 및 절차 안내를 요청합니다.</span></label><label className="flex gap-2.5 text-xs text-ink-soft"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)} className="mt-0.5"/><span>후원 의향 확인을 위한 개인정보 수집·이용에 동의합니다.</span></label>{error&&<p className="text-xs font-bold text-red-600">{error}</p>}<button disabled={busy} className="w-full py-3.5 rounded-xl bg-primary text-primary-ink font-extrabold text-sm disabled:opacity-50">{busy?'접수 중...':'후원 의향 등록'}</button></form>}</div></section>
 </div></div>;
};
const Info=({icon:Icon,title,text}:{icon:React.ElementType;title:string;text:string})=><div className="bg-paper-card border border-line rounded-2xl p-5"><Icon className="w-5 h-5 text-primary-ink"/><h3 className="font-bold text-ink mt-3">{title}</h3><p className="text-sm text-ink-soft leading-relaxed mt-2">{text}</p></div>;
const Field=({label,children}:{label:string;children:React.ReactNode})=><div className="space-y-1.5"><label className="text-xs font-bold text-ink">{label}</label>{children}</div>;
const inputCls='w-full px-3.5 py-3 rounded-xl border border-line bg-paper text-sm focus:outline-none focus:border-primary focus-visible:ring-2 focus-visible:ring-primary';
