import React, { useState } from 'react';
import { useValueTogether } from '../context/ValueTogetherContext';
import { PageBanner } from '../components/common/PageBanner';
import { CheckCircle2, Users, WalletCards, Vote, Send } from 'lucide-react';
import { checkRateLimit } from '../utils/spamGuard';

const TYPES = ['생산자조합원','소비자조합원','직원조합원','자원봉사자조합원','후원자조합원'] as const;
export const MembershipPage: React.FC = () => {
  const { submitMembershipApplication } = useValueTogether();
  const [memberType,setMemberType]=useState<typeof TYPES[number]>('소비자조합원'); const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [email,setEmail]=useState(''); const [organization,setOrganization]=useState(''); const [shares,setShares]=useState(1); const [agreed,setAgreed]=useState(false); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState('');
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!agreed){setError('개인정보 수집·이용에 동의해 주세요.');return;} if(!name.trim()||!phone.trim()){setError('이름과 연락처를 입력해 주세요.');return;} if(shares<1||shares>100){setError('출자 좌수는 1~100좌 범위에서 입력해 주세요.');return;} const limit=checkRateLimit('gachihamkke_membership_submit',3,10*60*1000);if(!limit.allowed){setError('잠시 후 다시 신청해 주세요.');return;} setBusy(true);try{await submitMembershipApplication({memberType,name:name.trim(),phone:phone.trim(),email:email.trim()||undefined,organization:organization.trim()||undefined,desiredShareCount:shares,privacyAgreed:true});setDone(true);}catch{setError('신청 접수에 실패했습니다. 잠시 후 다시 시도해 주세요.');}finally{setBusy(false);}};
  return <div><PageBanner eyebrow="MEMBERSHIP" title="조합원 가입" description="가치함께의 활동에 조합원으로 함께해 주세요."/><div className="max-w-6xl mx-auto px-4 sm:px-6 py-10 sm:py-14 space-y-12">
    <section className="grid md:grid-cols-3 gap-4"><Info icon={Users} title="조합원 유형" text="생산자·소비자·직원·자원봉사자·후원자 조합원으로 구성됩니다."/><Info icon={WalletCards} title="출자금" text="정관상 출자 1좌의 금액은 500,000원입니다."/><Info icon={Vote} title="민주적 의사결정" text="출자좌수와 관계없이 조합원은 1인 1개의 의결권과 선거권을 가집니다."/></section>
    <section className="grid lg:grid-cols-[1fr_1.1fr] gap-8 items-start"><div className="space-y-5"><h2 className="font-display font-black text-2xl text-ink">가입 전에 확인하세요</h2><ul className="space-y-3 text-sm text-ink-soft">{['조합원 자격과 유형은 정관 및 조합의 실제 운영 기준을 따릅니다.','출자금은 후원금과 다른 개념이며, 출자 1좌는 500,000원입니다.','가입 신청 후 조합의 확인 절차를 거쳐 최종 가입 여부를 안내합니다.','탈퇴·출자금 반환 등은 정관 및 관계 법령에 따라 처리됩니다.'].map(x=><li key={x} className="flex gap-2.5"><CheckCircle2 className="w-4 h-4 text-secondary-ink shrink-0 mt-0.5"/><span>{x}</span></li>)}</ul></div>
    <div className="bg-paper-card border border-line rounded-3xl p-6 sm:p-8">{done?<div className="py-10 text-center"><CheckCircle2 className="w-12 h-12 text-secondary-ink mx-auto"/><h2 className="font-display font-black text-xl text-ink mt-4">가입 신청이 접수되었습니다.</h2><p className="text-sm text-ink-soft mt-2">담당자가 확인 후 안내드리겠습니다.</p><button className="mt-5 text-xs font-bold text-primary-ink underline" onClick={()=>setDone(false)}>새 신청 작성</button></div>:<form onSubmit={submit} className="space-y-4"><h2 className="font-bold text-ink text-lg">조합원 가입 신청</h2><Field label="조합원 유형"><select className={inputCls} value={memberType} onChange={e=>setMemberType(e.target.value as any)}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></Field><div className="grid sm:grid-cols-2 gap-4"><Field label="이름 *"><input className={inputCls} value={name} onChange={e=>setName(e.target.value)} required/></Field><Field label="연락처 *"><input className={inputCls} value={phone} onChange={e=>setPhone(e.target.value)} required/></Field></div><Field label="이메일"><input type="email" className={inputCls} value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="소속/기관"><input className={inputCls} value={organization} onChange={e=>setOrganization(e.target.value)}/></Field><Field label="희망 출자 좌수"><input type="number" min={1} max={100} className={inputCls} value={shares} onChange={e=>setShares(Number(e.target.value)||1)}/><p className="text-[11px] text-ink-soft mt-1">1좌 500,000원 · 총 출자 예정액 {(shares * 500000).toLocaleString('ko-KR')}원</p></Field><label className="flex gap-2.5 text-xs text-ink-soft"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)} className="mt-0.5"/><span>가입 신청 처리를 위한 개인정보 수집·이용에 동의합니다.</span></label>{error&&<p className="text-xs font-bold text-red-600">{error}</p>}<button disabled={busy} className="w-full py-3.5 rounded-xl bg-primary text-primary-ink font-extrabold text-sm disabled:opacity-50 inline-flex items-center justify-center gap-2">{busy?'접수 중...':<><Send className="w-4 h-4"/> 가입 신청하기</>}</button></form>}</div></section>
  </div></div>;
};
const Info=({icon:Icon,title,text}:{icon:React.ElementType;title:string;text:string})=><div className="bg-paper-card border border-line rounded-2xl p-5"><Icon className="w-5 h-5 text-primary-ink"/><h3 className="font-bold text-ink mt-3">{title}</h3><p className="text-sm text-ink-soft leading-relaxed mt-2">{text}</p></div>;
const Field=({label,children}:{label:string;children:React.ReactNode})=><div className="space-y-1.5"><label className="text-xs font-bold text-ink">{label}</label>{children}</div>;
const inputCls='w-full px-3.5 py-3 rounded-xl border border-line bg-paper text-sm focus:outline-none focus:border-primary focus-visible:ring-2 focus-visible:ring-primary';
